/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fpoly.ui;

import com.fpoly.dao.UserDao;
import com.fpoly.entity.User;
import com.fpoly.utils.MsgBox;
import static com.fpoly.utils.XAuth.currentUser;
import com.poly.DaoImpl.UserDaoImpl;

/**
 *
 * @author X1 Carbon
 */
public class DoiMatKhauForm extends javax.swing.JFrame {

    private User user; // Biến để lưu thông tin người dùng được truyền vào
    private UserDao dao = new UserDaoImpl(); // Khởi tạo DAO

    /**
     * Creates new form DoiMatKhauForm
     */
    public DoiMatKhauForm(User user) {
        initComponents();
        setLocationRelativeTo(null);
        this.user = user;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtOldPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtXacNhanPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ĐỔI MẬT KHẨU");

        jLabel2.setText("Mật Khẩu Cũ:");

        jLabel3.setText("Mật khẩu Mới:");

        jLabel4.setText("Xác Nhận Lại Mật Khẩu Mới:");

        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtOldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXacNhanPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnXacNhan)
                        .addGap(68, 68, 68)
                        .addComponent(btnCancel)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtXacNhanPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(btnCancel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldPasswordActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        ChangePass();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
      Cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DoiMatKhauForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtOldPassword;
    private javax.swing.JPasswordField txtXacNhanPassword;
    // End of variables declaration//GEN-END:variables

    // TRONG DoiMatKhauForm.java

public void ChangePass() {
    if (this.user == null) {
        MsgBox.alert(this, "Lỗi hệ thống: Không xác định được người dùng đang đăng nhập.");
        this.dispose();
        return;
    }

    // 1. Lấy dữ liệu và loại bỏ khoảng trắng dư thừa
    String oldPassword = new String(txtOldPassword.getPassword()).trim(); 
    String newPassword = new String(txtNewPassword.getPassword()).trim(); 
    String confirmPassword = new String(txtXacNhanPassword.getPassword()).trim(); 

    String currentPassword = user.getPassword() != null ? user.getPassword().trim() : "NULL_OR_EMPTY"; 
    
    // ===============================================
    // <<< DEBUG START - DÙNG ĐỂ TÌM LỖI >>>
    System.out.println("================= DEBUG MAT KHAU =================");
    System.out.println("1. Mật khẩu cũ nhập vào (oldPassword): [" + oldPassword + "]");
    System.out.println("2. Mật khẩu cũ lưu trong User object (currentPassword): [" + currentPassword + "]");
    System.out.println("3. Độ dài (Nhập vào / Lưu trữ): " + oldPassword.length() + " / " + currentPassword.length());
    System.out.println("==================================================");
    // <<< DEBUG END >>>
    // ===============================================

    // 2.1. Kiểm tra trường rỗng
    if (oldPassword.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
        MsgBox.alert(this, "Vui lòng nhập đầy đủ Mật khẩu cũ, Mật khẩu mới và Xác nhận mật khẩu!");
        return;
    }

    // 2.2. Kiểm tra Mật khẩu cũ (CHỈ CÓ MỘT LẦN KIỂM TRA)
    if (!oldPassword.equals(currentPassword)) {
        MsgBox.alert(this, "Mật khẩu cũ không đúng. Vui lòng kiểm tra lại!");
        return;
    }
    
    // 2.3. Kiểm tra Mật khẩu mới và Xác nhận mật khẩu
    if (!newPassword.equals(confirmPassword)) {
        MsgBox.alert(this, "Xác nhận mật khẩu mới không khớp. Vui lòng nhập lại!");
        return;
    }

    // 2.4. Kiểm tra Mật khẩu mới có trùng Mật khẩu cũ không
    if (newPassword.equals(oldPassword)) {
        MsgBox.alert(this, "Mật khẩu mới phải khác Mật khẩu cũ.");
        return;
    }

    // 2.5. (Tùy chọn) Kiểm tra độ dài/phức tạp
    if (newPassword.length() < 6) {
        MsgBox.alert(this, "Mật khẩu mới phải có ít nhất 6 ký tự.");
        return;
    }

    // 3. Cập nhật mật khẩu mới vào cơ sở dữ liệu
    try {
        user.setPassword(newPassword); 
        dao.update(user); 

        MsgBox.alert(this, "Đổi mật khẩu thành công!");
        this.dispose();
    } catch (Exception e) {
        MsgBox.alert(this, "Lỗi cập nhật mật khẩu: " + e.getMessage());
        e.printStackTrace();
    }
}

    public void Cancel() {
        // Thêm hộp thoại xác nhận
        if (MsgBox.confirm(this, "Bạn có muốn Hủy thao tác Đổi Mật Khẩu không?")) {
             this.dispose();
        }
    }
}
