/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fpoly.ui;

import com.fpoly.DaoImpl.BorrowRequestDaoImpl;
import com.fpoly.entity.BorrowRequest;
import java.awt.Color;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X1 Carbon
 */
public class LichSuMuonForm extends javax.swing.JInternalFrame {
     private final Color DEFAULT_BUTTON_COLOR = new Color(210, 180, 140); // Màu HOVER: NÂU NHẠT
    private final Color HOVER_BUTTON_COLOR = new Color(255, 255, 255); // Màu Mặc định: TRẮNG
    /**
     * Creates new form LichSuMuonForm
     */
    public LichSuMuonForm() {
        initComponents();
        setResizable(false);
        applyHoverEffect(btnReloadBang, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
        applyHoverEffect(btnXemChiTiet, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblYeuCauMuon = new javax.swing.JTable();
        btnXemChiTiet = new javax.swing.JButton();
        btnReloadBang = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 112, 76));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lịch Sử Mượn");

        tblYeuCauMuon.setBackground(new java.awt.Color(210, 180, 140));
        tblYeuCauMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Yêu Cầu", "Mã Sinh Viên", "Mã Sách", "Tên Sách", "Ngày Mượn", "Trạng Thái", "Họ Và Tên", "MSSV", "Email", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(tblYeuCauMuon);

        btnXemChiTiet.setText("Xem Chi Tiết ");
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        btnReloadBang.setText("Reload bảng");
        btnReloadBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadBangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(503, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(btnReloadBang)
                        .addGap(353, 353, 353))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnReloadBang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadBangActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_btnReloadBangActionPerformed

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        // TODO add your handling code here:
        xemChiTiet();
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichSuMuonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichSuMuonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichSuMuonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichSuMuonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LichSuMuonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReloadBang;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    public javax.swing.JTable tblYeuCauMuon;
    // End of variables declaration//GEN-END:variables

public void loadTable() {
    try {
        BorrowRequestDaoImpl dao = new BorrowRequestDaoImpl();
        List<BorrowRequest> list = dao.selectAll();

        // Khởi tạo model và đặt tiêu đề cột
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "RequestID", "UserID", "Họ và Tên", "MSSV", "Email", "SĐT", "Mã Sách", "Số Lượng", "Ngày Mượn", "Trạng Thái", "Ghi Chú"
        });

        // Thêm dữ liệu vào bảng
        for (BorrowRequest br : list) {
            model.addRow(new Object[]{
                br.getRequestID(),
                br.getUserID(),
                br.getHoTen(),
                br.getMSSV(),
                br.getEmail(),
                br.getPhoneNumber(),
                br.getMaSach(),
                br.getSoLuong(),
                br.getRequestDate(),
                br.getStatus(),
                br.getNote()
            });
        }

        // Gán model cho JTable
        tblYeuCauMuon.setModel(model);

        // Tùy chọn: chỉnh lại độ rộng cột, căn giữa, ... nếu muốn
        // tblYeuCauMuon.getColumnModel().getColumn(0).setPreferredWidth(50);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi load dữ liệu BorrowRequest!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}

private void applyHoverEffect(JButton button, Color defaultColor, Color hoverColor) {

    button.setForeground(Color.BLACK);
    // THÊM DÒNG NÀY: Đặt màu nền ban đầu
    button.setBackground(defaultColor); 

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hoverColor);
            button.setForeground(Color.BLACK);
            setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(defaultColor);
            button.setForeground(Color.BLACK);
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    });
}
private void xemChiTiet() {
    int row = tblYeuCauMuon.getSelectedRow();

    if (row < 0) {
        JOptionPane.showMessageDialog(this,
                "Vui lòng chọn một phiếu mượn!",
                "Thông báo",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Cột 0 = RequestID
    int requestID = Integer.parseInt(
            tblYeuCauMuon.getValueAt(row, 0).toString()
    );

    try {
        BorrowRequestDaoImpl dao = new BorrowRequestDaoImpl();
        BorrowRequest br = dao.selectById(requestID);

        if (br != null) {
            XemChiTietMuonSachForm form = new XemChiTietMuonSachForm();
            form.setForm(br);
            form.setLocationRelativeTo(this);
            form.setVisible(true);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Không thể xem chi tiết phiếu mượn!",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
    }
}


}
