/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fpoly.ui;


import com.fpoly.entity.User;
import com.fpoly.utils.XAuth;
import static com.fpoly.utils.XAuth.currentUser;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X1 Carbon
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainForm(User currentUser) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        phanQuyen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        tabMain = new javax.swing.JTabbedPane();
        tabUserManager = new javax.swing.JPanel();
        btnQuanLiNguoiDung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        tabBaoCaoThongKe = new javax.swing.JPanel();
        tabDanhSachQuaHan = new javax.swing.JPanel();
        tabMuonSach = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Trang Chính Quản Lí Thư Viện");

        btnLogOut.setText("ĐĂNG XUẤT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnQuanLiNguoiDung.setText("Chỉnh Sửa Tài Khoản");
        btnQuanLiNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLiNguoiDungActionPerformed(evt);
            }
        });

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "UserId", "Username", "Password", "Họ Và tên", "Email", "RoleID", "RoleName"
            }
        ));
        jScrollPane1.setViewportView(tblUser);

        jButton1.setText("LỌC");

        javax.swing.GroupLayout tabUserManagerLayout = new javax.swing.GroupLayout(tabUserManager);
        tabUserManager.setLayout(tabUserManagerLayout);
        tabUserManagerLayout.setHorizontalGroup(
            tabUserManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabUserManagerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuanLiNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(tabUserManagerLayout.createSequentialGroup()
                .addGroup(tabUserManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabUserManagerLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(tabUserManagerLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        tabUserManagerLayout.setVerticalGroup(
            tabUserManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabUserManagerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(tabUserManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLiNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        tabMain.addTab("Trang Quản Lí Tài Khoản", tabUserManager);

        javax.swing.GroupLayout tabBaoCaoThongKeLayout = new javax.swing.GroupLayout(tabBaoCaoThongKe);
        tabBaoCaoThongKe.setLayout(tabBaoCaoThongKeLayout);
        tabBaoCaoThongKeLayout.setHorizontalGroup(
            tabBaoCaoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        tabBaoCaoThongKeLayout.setVerticalGroup(
            tabBaoCaoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        tabMain.addTab("Báo Cáo Thống Kê", tabBaoCaoThongKe);

        javax.swing.GroupLayout tabDanhSachQuaHanLayout = new javax.swing.GroupLayout(tabDanhSachQuaHan);
        tabDanhSachQuaHan.setLayout(tabDanhSachQuaHanLayout);
        tabDanhSachQuaHanLayout.setHorizontalGroup(
            tabDanhSachQuaHanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        tabDanhSachQuaHanLayout.setVerticalGroup(
            tabDanhSachQuaHanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        tabMain.addTab("Danh Sách Quá Hạn", tabDanhSachQuaHan);

        javax.swing.GroupLayout tabMuonSachLayout = new javax.swing.GroupLayout(tabMuonSach);
        tabMuonSach.setLayout(tabMuonSachLayout);
        tabMuonSachLayout.setHorizontalGroup(
            tabMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        tabMuonSachLayout.setVerticalGroup(
            tabMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        tabMain.addTab("Mượn Sách", tabMuonSach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        tabMain.addTab("Duyệt Yêu Cầu Mượn/Trả Sách", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        tabMain.addTab("Gia Hạn Mượn", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        tabMain.addTab("Trả Sách", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        tabMain.addTab("Quản Lí Kho Sách", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(916, 916, 916)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tabMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnQuanLiNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiNguoiDungActionPerformed
        // TODO add your handling code here:
        openUser();
    }//GEN-LAST:event_btnQuanLiNguoiDungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm(XAuth.currentUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnQuanLiNguoiDung;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel tabBaoCaoThongKe;
    private javax.swing.JPanel tabDanhSachQuaHan;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JPanel tabMuonSach;
    private javax.swing.JPanel tabUserManager;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

//======================XỬ LÝ CÁC NÚT CHỨC NĂNG========================//  
    //=====Nút Đăng Xuất=====//
    public void logout() {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận đăng xuất",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose(); // Đóng form Admin hiện tại
            new LoginForm().setVisible(true); // Mở lại form đăng nhập
        }
    }

    //=====Nút Quản Lí Người Dùng=====//
    public void openUser() {
        // Mở form Quản Lý Người Dùng mà không đóng MainForm
        QuanLyNguoiDungForm userForm = new QuanLyNguoiDungForm();
        userForm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // chỉ đóng form này thôi
        userForm.setVisible(true);
    }
    //=====Nút Quản Lí Kho Sách=====//

    public void openBookManager() {
        //Mở form Quản Lý Kho Sách mà không đóng MainForm
        QuanLyKhoSachForm bookForm = new QuanLyKhoSachForm();
        bookForm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        bookForm.setVisible(true);
    }

    //=====Nút Quản Lí Báo Cáo Thống Kê=====//
    
    
    //=====Nút Quản Lí Thông Báo Quá Hạn=====//
    public void openThongBaoQuaHan() {
        //Mở form Quản Lý Thông Báo Quá Hạn mà không đóng MainForm
        QuanLyThongBaoQuaHan thongbaoquahanForm = new QuanLyThongBaoQuaHan();
        thongbaoquahanForm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        thongbaoquahanForm.setVisible(true);
    }

private void phanQuyen() {
    int role = currentUser.getRoleID();
    // Admin = 1 -> Full quyền
    if (role == 1) {
        return;
    }

    // Thủ thư = 2 -> Ẩn tab quản lý tài khoản
    if (role == 2) {
        removeTabIfExists("Trang Quản Lí Tài Khoản");
        removeTabIfExists("Mượn Sách");
        removeTabIfExists("Trả Sách");
        removeTabIfExists("Gia Hạn Mượn");
        
    }

    // Member = 3 -> Chỉ giữ lại tab Mượn Sách
    if (role == 3) {
        removeTabIfExists("Trang Quản Lí Tài Khoản");
        removeTabIfExists("Báo Cáo Thống Kê");
        removeTabIfExists("Danh Sách Quá Hạn");
        removeTabIfExists("Duyệt Yêu Cầu Mượn/Trả Sách");
        // Tab Mượn Sách được giữ lại
    }
}

private void removeTabIfExists(String title) {
    for (int i = 0; i < tabMain.getTabCount(); i++) {
        if (tabMain.getTitleAt(i).equalsIgnoreCase(title)) {
            tabMain.remove(i);
            break;
        }
    }
}
}
