/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fpoly.ui;

import com.fpoly.entity.User;
import com.fpoly.utils.XAuth;
import static com.fpoly.utils.XAuth.currentUser;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author X1 Carbon
 */
public class MainForm extends javax.swing.JFrame {

    private User loggedInUser;// Màu HOVER: NÂU NHẠT
    private final Color DEFAULT_BUTTON_COLOR = new Color(210, 180, 140); // Màu HOVER: NÂU NHẠT
    private final Color HOVER_BUTTON_COLOR = new Color(255, 255, 255); // Màu Mặc định: TRẮNG

    /**
     * Creates new form MainPage
     */
    public MainForm(User currentUser) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        // Gán đối tượng User được truyền vào cho biến instance
        this.loggedInUser = currentUser;
        XAuth.currentUser = currentUser; // Cần thiết để các form khác dùng XAuth

        String roleName = mapRoleIDToName(currentUser.getRoleID());
        jLabel2.setText("Tài Khoản: " + currentUser.getUsername());
        jLabel3.setText("Quyền: " + roleName);

        applyHoverEffect(btnChangePass, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
        applyHoverEffect(btnLogOut, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);

        openTraSach();
        openQLQuaHan();
        openMuonsach();
        openUser();
        openBaoCaoThongKe();
        openBookManager();
        openThongBaoQuaHan();
        phanQuyen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        tabBaoCaoThongKe = new javax.swing.JPanel();
        tabDanhSachQuaHan = new javax.swing.JPanel();
        tabMuonSach = new javax.swing.JPanel();
        tabTraSach = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tabUserManager = new javax.swing.JPanel();
        QLQuaHan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabMain.setBackground(new java.awt.Color(210, 180, 140));
        tabMain.setForeground(new java.awt.Color(0, 0, 0));

        tabBaoCaoThongKe.setBackground(new java.awt.Color(153, 112, 76));

        javax.swing.GroupLayout tabBaoCaoThongKeLayout = new javax.swing.GroupLayout(tabBaoCaoThongKe);
        tabBaoCaoThongKe.setLayout(tabBaoCaoThongKeLayout);
        tabBaoCaoThongKeLayout.setHorizontalGroup(
            tabBaoCaoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        tabBaoCaoThongKeLayout.setVerticalGroup(
            tabBaoCaoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        tabMain.addTab("Báo Cáo Thống Kê", tabBaoCaoThongKe);

        tabDanhSachQuaHan.setBackground(new java.awt.Color(153, 112, 76));

        javax.swing.GroupLayout tabDanhSachQuaHanLayout = new javax.swing.GroupLayout(tabDanhSachQuaHan);
        tabDanhSachQuaHan.setLayout(tabDanhSachQuaHanLayout);
        tabDanhSachQuaHanLayout.setHorizontalGroup(
            tabDanhSachQuaHanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        tabDanhSachQuaHanLayout.setVerticalGroup(
            tabDanhSachQuaHanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        tabMain.addTab("Danh Sách /Thông Báo Quá Hạn", tabDanhSachQuaHan);

        tabMuonSach.setBackground(new java.awt.Color(153, 112, 76));

        javax.swing.GroupLayout tabMuonSachLayout = new javax.swing.GroupLayout(tabMuonSach);
        tabMuonSach.setLayout(tabMuonSachLayout);
        tabMuonSachLayout.setHorizontalGroup(
            tabMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        tabMuonSachLayout.setVerticalGroup(
            tabMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        tabMain.addTab("Mượn Sách", tabMuonSach);

        tabTraSach.setBackground(new java.awt.Color(153, 112, 76));

        javax.swing.GroupLayout tabTraSachLayout = new javax.swing.GroupLayout(tabTraSach);
        tabTraSach.setLayout(tabTraSachLayout);
        tabTraSachLayout.setHorizontalGroup(
            tabTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        tabTraSachLayout.setVerticalGroup(
            tabTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        tabMain.addTab("Lịch Sử Mượn", tabTraSach);

        jPanel5.setBackground(new java.awt.Color(153, 112, 76));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        tabMain.addTab("Quản Lí Kho Sách", jPanel5);

        tabUserManager.setBackground(new java.awt.Color(153, 112, 76));

        javax.swing.GroupLayout tabUserManagerLayout = new javax.swing.GroupLayout(tabUserManager);
        tabUserManager.setLayout(tabUserManagerLayout);
        tabUserManagerLayout.setHorizontalGroup(
            tabUserManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        tabUserManagerLayout.setVerticalGroup(
            tabUserManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        tabMain.addTab("Trang Quản Lí Tài Khoản", tabUserManager);

        QLQuaHan.setBackground(new java.awt.Color(153, 112, 76));

        javax.swing.GroupLayout QLQuaHanLayout = new javax.swing.GroupLayout(QLQuaHan);
        QLQuaHan.setLayout(QLQuaHanLayout);
        QLQuaHanLayout.setHorizontalGroup(
            QLQuaHanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        QLQuaHanLayout.setVerticalGroup(
            QLQuaHanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        tabMain.addTab("Quản Lí Thông Báo Quá Hạn", QLQuaHan);

        jPanel1.add(tabMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 146, 1250, 610));

        jPanel2.setBackground(new java.awt.Color(153, 112, 76));

        btnLogOut.setText("ĐĂNG XUẤT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gemini_Generated_Image_n80j7xn80j7xn80j-removebg-preview.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Trang Chính Quản Lí Thư Viện");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tài Khoản: ");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Quyền:");

        btnChangePass.setText("Đổi Mật Khẩu");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnChangePass))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(btnChangePass))
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 624, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        openChangePasswordDialog();
    }//GEN-LAST:event_btnChangePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm(XAuth.currentUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QLQuaHan;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel tabBaoCaoThongKe;
    private javax.swing.JPanel tabDanhSachQuaHan;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JPanel tabMuonSach;
    private javax.swing.JPanel tabTraSach;
    private javax.swing.JPanel tabUserManager;
    // End of variables declaration//GEN-END:variables

//======================XỬ LÝ CÁC NÚT CHỨC NĂNG========================//  
    //=====Nút Đăng Xuất=====//
    public void logout() {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận đăng xuất",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose(); // Đóng form Admin hiện tại
            new LoginForm().setVisible(true); // Mở lại form đăng nhập
        }
    }

    //=====Load Quản Lí Người Dùng lên panel=====//
    public void openUser() {
        // 1. Chỉ định Panel đích trong MainForm
        javax.swing.JPanel tabPanel = tabUserManager; // Tên biến Panel của tab "Trang Quản Lí Tài Khoản"

        // 2. Dọn dẹp Panel trước khi nhúng form mới
        if (tabPanel.getComponentCount() > 0) {
            tabPanel.removeAll();
        }

        // 3. Thiết lập Layout cho Panel chứa (QUAN TRỌNG: để JInternalFrame lấp đầy)
        tabPanel.setLayout(new java.awt.BorderLayout());

        // 4. Khởi tạo JInternalFrame mới (Sau khi đã đổi QuanLyNguoiDungForm sang JInternalFrame)
        QuanLyNguoiDungForm userForm = new QuanLyNguoiDungForm();

        // 5. Thiết lập JInternalFrame ở chế độ tối đa (lấp đầy Panel)
        try {
            userForm.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            // Có thể bỏ qua lỗi này
        }

        // 6. Thêm JInternalFrame vào vị trí CENTER
        tabPanel.add(userForm, java.awt.BorderLayout.CENTER);

        // 7. Hiển thị và cập nhật giao diện
        userForm.setVisible(true);
        tabPanel.revalidate();
        tabPanel.repaint();
    }

    private void phanQuyen() {
        int role = currentUser.getRoleID();
        // Admin = 1 -> Full quyền
        if (role == 1) {
            return;
        }

        // Thủ thư = 2 -> Ẩn tab quản lý tài khoản
        if (role == 2) {
            removeTabIfExists("Trang Quản Lí Tài Khoản");
            removeTabIfExists("Mượn Sách");
            removeTabIfExists("Trả Sách");
            removeTabIfExists("Danh Sách/Thông Báo Quá Hạn");

        }

        // Member = 3 -> Chỉ giữ lại tab Mượn Sách
        if (role == 3) {
            removeTabIfExists("Trang Quản Lí Tài Khoản");
            removeTabIfExists("Báo Cáo Thống Kê");
            removeTabIfExists("Duyệt Yêu Cầu Mượn/Trả Sách");
            removeTabIfExists("Quản Lí Kho Sách");
            removeTabIfExists("Quản Lí Thông Báo Quá Hạn");
            // Tab Mượn Sách được giữ lại
        }
    }

    private void removeTabIfExists(String title) {
        for (int i = 0; i < tabMain.getTabCount(); i++) {
            if (tabMain.getTitleAt(i).equalsIgnoreCase(title)) {
                tabMain.remove(i);
                break;
            }
        }
    }

    public void openBaoCaoThongKe() {
        // 1. Khởi tạo form Thống kê
        QuanLyBaoCaoThongKe baoCaoInternalFrame = new QuanLyBaoCaoThongKe();

        // 2. Lấy JPanel của tab Báo Cáo Thống Kê
        javax.swing.JPanel tabPanel = tabBaoCaoThongKe;

        // 3. Sử dụng BorderLayout để InternalFrame lấp đầy Panel
        tabPanel.removeAll();
        tabPanel.setLayout(new java.awt.BorderLayout());

        // 4. Thêm InternalFrame vào Panel
        tabPanel.add(baoCaoInternalFrame, java.awt.BorderLayout.CENTER);

        // 5. Hiển thị InternalFrame (rất quan trọng)
        baoCaoInternalFrame.setVisible(true);

        // 6. Cập nhật lại giao diện
        tabPanel.revalidate();
        tabPanel.repaint();
    }

// Trong MainForm.java
    public void openBookManager() {
        javax.swing.JPanel tabPanel = jPanel5; // jPanel5 là tab "Quản Lí Kho Sách"

        // Nếu chưa có, cần thêm 3 dòng này:
        tabPanel.removeAll();
        tabPanel.setLayout(new java.awt.BorderLayout()); // <--- Dòng RẤT QUAN TRỌNG

        QuanLyKhoSachForm bookForm = new QuanLyKhoSachForm();

        // Thêm JInternalFrame vào vị trí CENTER
        tabPanel.add(bookForm, java.awt.BorderLayout.CENTER); // <--- Dòng RẤT QUAN TRỌNG

        bookForm.setVisible(true);
        tabPanel.revalidate();
        tabPanel.repaint();
    }

    public void openThongBaoQuaHan() {
        // THAY THẾ 'jPanelThongBao' bằng tên biến Panel/Tab trong MainForm
        // nơi ku em muốn hiển thị form Thông báo Quá hạn.
        javax.swing.JPanel tabPanel = tabDanhSachQuaHan; // Ví dụ: Có thể là tab Danh Sách Quá Hạn (tabDanhSachQuaHan)

        // 1. Dọn dẹp Panel trước khi nhúng form mới
        if (tabPanel.getComponentCount() > 0) {
            tabPanel.removeAll();
        }

        // 2. Thiết lập Layout cho Panel chứa (QUAN TRỌNG: để JInternalFrame lấp đầy)
        tabPanel.setLayout(new java.awt.BorderLayout());

        // 3. Khởi tạo JInternalFrame với TÊN LỚP CHÍNH XÁC
        ThongBaoQuanHanFrom thongBaoForm = new ThongBaoQuanHanFrom();

        // 4. Thiết lập JInternalFrame ở chế độ tối đa (lấp đầy Panel)
        try {
            thongBaoForm.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            // Log lỗi hoặc bỏ qua
        }

        // 5. Thêm JInternalFrame vào vị trí CENTER
        tabPanel.add(thongBaoForm, java.awt.BorderLayout.CENTER);

        // 6. Hiển thị và cập nhật giao diện
        thongBaoForm.setVisible(true);
        tabPanel.revalidate();
        tabPanel.repaint();
    }

// Thêm hàm này vào cuối lớp MainForm
    private String mapRoleIDToName(int roleID) {
        switch (roleID) {
            case 1:
                return "Admin";
            case 2:
                return "Thủ Thư";
            case 3:
                return "Member";
            default:
                return "Không rõ";
        }
    }

// Thêm hàm này vào phần xử lý chức năng trong lớp MainForm
// Sửa lại phương thức này:
    private void openChangePasswordDialog() {
        // Lấy user từ biến instance đã lưu trong constructor (Cách an toàn nhất)
        User userToChange = this.loggedInUser;

        // Nếu ku em không dùng biến instance, dùng XAuth.currentUser
        if (userToChange == null) {
            userToChange = XAuth.currentUser;
        }

        if (userToChange == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin người dùng đang đăng nhập.", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // GỌI CONSTRUCTOR ĐÚNG CÁCH VÀ TRUYỀN USER VÀO:
        DoiMatKhauForm changePassDialog = new DoiMatKhauForm(userToChange);
        changePassDialog.setVisible(true);
    }

    public void openMuonsach() {
        javax.swing.JPanel tabPanel = tabMuonSach;

        if (tabPanel.getComponentCount() > 0) {
            tabPanel.removeAll();
        }

        tabPanel.setLayout(new java.awt.BorderLayout());

        MuonSachForm muonSachForm = new MuonSachForm();

        try {
            muonSachForm.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
        }

        tabPanel.add(muonSachForm, java.awt.BorderLayout.CENTER);

        muonSachForm.setVisible(true);
        tabPanel.revalidate();
        tabPanel.repaint();
    }
    public void openQLQuaHan() {
    javax.swing.JPanel tabPanel = QLQuaHan; 

    if (tabPanel.getComponentCount() > 0) {
        tabPanel.removeAll();
    }

    tabPanel.setLayout(new java.awt.BorderLayout());

    QuanLyThongBaoQuaHan quanLyQuaHanForm = new QuanLyThongBaoQuaHan();

    try {
        quanLyQuaHanForm.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        
    }

    tabPanel.add(quanLyQuaHanForm, java.awt.BorderLayout.CENTER);

    quanLyQuaHanForm.setVisible(true);
    tabPanel.revalidate();
    tabPanel.repaint();
}
    public void openTraSach() {
    // 1. Lấy JPanel của tab "Mượn Sách"
    javax.swing.JPanel tabPanel = tabTraSach;

    // 2. Dọn dẹp panel trước khi nhúng form mới
    if (tabPanel.getComponentCount() > 0) {
        tabPanel.removeAll();
    }

    // 3. Thiết lập layout cho panel chứa (quan trọng)
    tabPanel.setLayout(new java.awt.BorderLayout());

    // 4. Khởi tạo JInternalFrame mới (Lịch Sử Mượn)
    LichSuMuonForm lichSuMuonForm = new LichSuMuonForm();

    // 5. Thiết lập JInternalFrame ở chế độ tối đa (lấp đầy panel)
    try {
        lichSuMuonForm.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        // Log lỗi hoặc bỏ qua
    }

    // 6. Thêm JInternalFrame vào vị trí CENTER
    tabPanel.add(lichSuMuonForm, java.awt.BorderLayout.CENTER);

    // 7. Hiển thị và cập nhật giao diện
    lichSuMuonForm.setVisible(true);
    tabPanel.revalidate();
    tabPanel.repaint();
}
private void applyHoverEffect(JButton button, Color defaultColor, Color hoverColor) {

    button.setForeground(Color.BLACK);
    // THÊM DÒNG NÀY: Đặt màu nền ban đầu
    button.setBackground(defaultColor); 

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hoverColor);
            button.setForeground(Color.BLACK);
            setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(defaultColor);
            button.setForeground(Color.BLACK);
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    });
}
     
}
