/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fpoly.ui;

import com.fpoly.Dao.BookDAO;
import com.fpoly.entity.Category;
import com.fpoly.utils.MsgBox;
import com.poly.DaoImpl.BookDAOImpl;
import com.poly.DaoImpl.CategoryDAOImpl;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;

/**
 *
 * @author X1 Carbon
 */
public class MuonSachForm extends javax.swing.JInternalFrame {

    private BookDAO bookDAO;
    private final CategoryDAOImpl CategoryDAO;
     private final Color DEFAULT_BUTTON_COLOR = new Color(255, 255, 255); // Màu Mặc định: TRẮNG
    private final Color HOVER_BUTTON_COLOR = new Color(210, 180, 140); // Màu HOVER: NÂU NHẠT

    /**
     * Creates new form MuonSachForm
     */
    public MuonSachForm() {
        initComponents();
        tblBooks.getSelectionModel().addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting()) {
        fillFormFromTable();
    }
});

        this.bookDAO = new BookDAOImpl() {};
        this.CategoryDAO = new com.poly.DaoImpl.CategoryDAOImpl();

        // Gọi hàm tải dữ liệu (Phải gọi sau khi CategoryDAO được khởi tạo)
        loadDataToTable();
        loadDataToCboTheLoai(); 
        applyHoverEffect(btnSearch, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
        applyHoverEffect(btnTaoPhieu, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtTensach = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTheLoai = new javax.swing.JTextField();
        txtTenTacGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboTheLoai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnTaoPhieu = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 161, 104));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 32, 478, 32));

        btnSearch.setText("Tra Cứu Sách");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 32, 112, 31));

        tblBooks.setBackground(new java.awt.Color(210, 180, 140));
        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tên Tác Giả", "Thể Loại", "Số Lượng"
            }
        ));
        jScrollPane1.setViewportView(tblBooks);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 160, 710, 300));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 1152, 10));
        getContentPane().add(txtTensach, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 172, 325, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thông Tin Sách");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 110, -1, -1));

        txtTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTheLoaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 312, 325, 30));
        getContentPane().add(txtTenTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 242, 325, 30));

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        getContentPane().add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 382, 323, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tra Cứu Sách:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 32, -1, -1));

        getContentPane().add(cboTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 120, 170, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Thể Loại:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 123, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên Sách:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 150, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên Tác Giả:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 220, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thể Loại:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 290, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Lượng:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 360, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 112, 76));

        btnTaoPhieu.setText("Tạo Phiếu Mượn");
        btnTaoPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1047, Short.MAX_VALUE)
                .addComponent(btnTaoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(501, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1220, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTheLoaiActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnTaoPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhieuActionPerformed
        // TODO add your handling code here
        openTaoPhieuForm();
    }//GEN-LAST:event_btnTaoPhieuActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchBook();
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuonSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuonSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuonSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuonSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuonSachForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTaoPhieu;
    private javax.swing.JComboBox<Category> cboTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenTacGia;
    private javax.swing.JTextField txtTensach;
    private javax.swing.JTextField txtTheLoai;
    // End of variables declaration//GEN-END:variables
    private void loadDataToCboTheLoai() {
        DefaultComboBoxModel<Category> model = new DefaultComboBoxModel<>();

        try {
            // 1. Thêm mục mặc định (CategoryID = 0)
            model.addElement(new Category(0, "--- Tất Cả Thể Loại ---"));

            // 2. Lấy danh sách thể loại từ DB (ĐÃ SỬA LỖI GỌI DAO)
            List<Category> categories = CategoryDAO.selectAll();

            // 3. Thêm các Category vào Model
            for (Category cat : categories) {
                model.addElement(cat);
            }

            // 4. Đặt Model vào JComboBox
            cboTheLoai.setModel(model);

            // 5. Đặt mục chọn mặc định là mục đầu tiên
            cboTheLoai.setSelectedIndex(0);

        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi khi tải dữ liệu Thể loại: " + e.getMessage());
        }
    }

    private void loadDataToTable() {
        bookDAO.loadBooksToTable(tblBooks); // tblBooks là tên JTable của bạn
    }

   private void applyHoverEffect(JButton button, Color defaultColor, Color hoverColor) {

        button.setForeground(Color.BLACK);

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverColor);
                button.setForeground(Color.BLACK);
                setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(defaultColor);
                button.setForeground(Color.BLACK);
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }
        });
    }
   private void fillFormFromTable() {
    int row = tblBooks.getSelectedRow();
    if (row < 0) return;

    txtTensach.setText(tblBooks.getValueAt(row, 1).toString());
    txtTenTacGia.setText(tblBooks.getValueAt(row, 2).toString());
    txtTheLoai.setText(tblBooks.getValueAt(row, 3).toString());
    txtSoLuong.setText(tblBooks.getValueAt(row, 4).toString());
}
public void openTaoPhieuForm() {
    int row = tblBooks.getSelectedRow();
    if (row < 0) {
        MsgBox.alert(this, "Vui lòng chọn một sách trước khi tạo phiếu!");
        return;
    }

    // Lấy thông tin từ bảng
    int maSach = Integer.parseInt(tblBooks.getValueAt(row, 0).toString());
    String tenSach = tblBooks.getValueAt(row, 1).toString();
    String tacGia = tblBooks.getValueAt(row, 2).toString();
    String theLoai = tblBooks.getValueAt(row, 3).toString();
    int soLuong = Integer.parseInt(tblBooks.getValueAt(row, 4).toString());

    // Truyền dữ liệu sang form tạo phiếu
    TaoPhieuForm taoPhieu = new TaoPhieuForm(maSach, tenSach, tacGia, theLoai, soLuong);
    taoPhieu.setVisible(true);
}
public void searchBook() {
        try {
            String keyword = txtSearch.getText().trim();
            Category selectedCategory = (Category) cboTheLoai.getSelectedItem();
            int categoryID = selectedCategory.getCategoryID();

            // Gọi DAO để tìm kiếm và đổ dữ liệu lên JTable
            // Ku em cần đảm bảo hàm searchBooks(JTable, String, int) tồn tại trong BookDAOImpl
            bookDAO.searchBooks(tblBooks, keyword, categoryID);

            if (tblBooks.getRowCount() == 0) {
                MsgBox.alert(this, "Không tìm thấy sách nào khớp với từ khóa/thể loại đã chọn.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi trong quá trình tìm kiếm sách: " + e.getMessage());
        }
    }
   
}
