/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fpoly.ui;
// Khai báo biến DAO để dùng chung
import javax.swing.ImageIcon; // Import lớp ImageIcon
import java.awt.Image;
import com.fpoly.utils.MsgBox;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import com.fpoly.entity.Category;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import com.fpoly.Dao.BookDAO;
import com.poly.DaoImpl.BookDAOImpl;
import com.poly.DaoImpl.CategoryDAOImpl;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;


/**
 *
 * @author X1 Carbon
 */
public class QuanLyKhoSachForm extends javax.swing.JInternalFrame {
       private BookDAO bookDAO;
    private final CategoryDAOImpl CategoryDAO;
    private int categoryID;
    private final Color DEFAULT_BUTTON_COLOR = new Color(210, 180, 140); // Màu HOVER: NÂU NHẠT
    private final Color HOVER_BUTTON_COLOR = new Color(255, 255, 255); // Màu Mặc định: TRẮNG
        /**
     * Creates new form QuanLyKhoSach
     */
    public QuanLyKhoSachForm() {
        initComponents();
         applyHoverEffect(btnCapNhat, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
        applyHoverEffect(btnMoi, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
        applyHoverEffect(btnThemSach, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
        applyHoverEffect(btnTimKiem, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
        applyHoverEffect(btnXoa, DEFAULT_BUTTON_COLOR, HOVER_BUTTON_COLOR);
       
    // ...
    // Khởi tạo DAO
    this.bookDAO = new BookDAOImpl();
    this.CategoryDAO = new com.poly.DaoImpl.CategoryDAOImpl(); // <<< BỔ SUNG KHỞI TẠO NÀY

    // Gọi hàm tải dữ liệu (Phải gọi sau khi CategoryDAO được khởi tạo)
    loadDataToTable();
    loadDataToCboTheLoai(); // <<< BỔ SUNG GỌI NÀY
    // ...
      
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/books.jpg"));
        Image image = icon.getImage();
       
        Timer timer = new Timer(1000, new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        lblClock.setText(new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy").format(new Date()));
    }
});
timer.start();

    

        // Khởi tạo DAO
       this.bookDAO = new BookDAOImpl();
        
        // Gọi hàm tải dữ liệu
        loadDataToTable();
        // Thêm sự kiện click chuột vào bảng
        tblBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBooksMouseClicked(evt);
            }
            });
        txtMaSach.setEditable(false);
    }
    
    // Hàm mới để tải dữ liệu lên JTable
    private void loadDataToTable() {
        bookDAO.loadBooksToTable(tblBooks); // tblBooks là tên JTable của bạn
    }
    
    
    // PHƯƠNG THỨC HỖ TRỢ: Lấy dữ liệu và kiểm tra validation
private String[] getFormValues() { 
 String maSach = txtMaSach.getText().trim();
    String tenSach = txtTenSach.getText().trim();
    String tacGia = txtTacGia.getText().trim();
    String soLuong = txtSoLuong.getText().trim();

    Object selectedObject = cboTheLoai.getSelectedItem();
    String theLoaiName = "";

    if (selectedObject != null && selectedObject instanceof Category) {
        Category selectedCategory = (Category) selectedObject;
        if (selectedCategory.getCategoryID() > 0) {
            theLoaiName = selectedCategory.getCategoryName();
        }
    }

    if (tenSach.isEmpty() || tacGia.isEmpty() || theLoaiName.isEmpty() || soLuong.isEmpty()) {
        MsgBox.alert(this, "Vui lòng nhập đầy đủ thông tin (Tên sách, Tác giả, Thể loại, Số lượng).");
        return null;
    }
    
    try {
        Integer.parseInt(soLuong);
    } catch (NumberFormatException e) {
        MsgBox.alert(this, "Số Lượng phải là một số nguyên hợp lệ.");
        return null;
    }

    return new String[]{maSach, tenSach, tacGia, theLoaiName, soLuong};
}

// PHƯƠNG THỨC HỖ TRỢ: Làm mới form (gọi khi Thêm/Sửa/Xóa thành công)
private void clearForm() {
        // 1. Xóa các ô nhập liệu bên phải
    txtMaSach.setText("");
    txtTenSach.setText("");
    txtTacGia.setText("");
    txtSoLuong.setText("");
    
    cboTheLoai.setSelectedIndex(0); 

    txtTimKiem.setText("");
    
    this.loadDataToTable();
   
    // 2. Xóa ô tìm kiếm
    txtTimKiem.setText("");
    
    // 3. Tải lại toàn bộ dữ liệu gốc
    this.loadDataToTable();
}

        /**
     * 
        * 
        * Creates new form QuanLyKhoSach
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        javax.swing.JPanel btnLamMoi = new javax.swing.JPanel();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnThemSach = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        cboTheLoai = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 112, 76));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Kho Sách");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tìm Kiếm :");

        tblBooks.setBackground(new java.awt.Color(210, 180, 140));
        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tên Tác Giả", "Thể Loại ", "Số Lượng"
            }
        ));
        jScrollPane3.setViewportView(tblBooks);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnLamMoi.setBackground(new java.awt.Color(153, 112, 76));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã Sách :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tên Sách :");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tên Tác Giả :");

        jLabel6.setBackground(new java.awt.Color(153, 112, 76));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Thể Loại :");

        btnThemSach.setText("Thêm Sách");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Số Lượng :");

        btnMoi.setText("Làm mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm Thể Loại");

        javax.swing.GroupLayout btnLamMoiLayout = new javax.swing.GroupLayout(btnLamMoi);
        btnLamMoi.setLayout(btnLamMoiLayout);
        btnLamMoiLayout.setHorizontalGroup(
            btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLamMoiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLamMoiLayout.createSequentialGroup()
                        .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSach)
                            .addComponent(txtTenSach)))
                    .addGroup(btnLamMoiLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(txtSoLuong))
                    .addGroup(btnLamMoiLayout.createSequentialGroup()
                        .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnLamMoiLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLamMoiLayout.createSequentialGroup()
                                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTacGia)
                            .addGroup(btnLamMoiLayout.createSequentialGroup()
                                .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))))
                    .addGroup(btnLamMoiLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)))
                .addGap(14, 14, 14))
        );
        btnLamMoiLayout.setVerticalGroup(
            btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLamMoiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi))
                .addGap(18, 18, 18)
                .addGroup(btnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnThemSach))
                .addGap(29, 29, 29))
        );

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        // TODO add your handling code here:
//        BanThemSach ban = new BanThemSach();
//        ban.setVisible(true);
// 1. Lấy dữ liệu và kiểm tra validation
        String[] values = getFormValues();
        
        // 2. Nếu dữ liệu hợp lệ (values không phải là null)
        if (values != null) {
            // Lấy các giá trị cần thiết để thêm sách (Bỏ qua MaSach - values[0])
            String tenSach = values[1];
            String tacGia = values[2];
            String theLoai = values[3];
            int soLuong = Integer.parseInt(values[4]);
            
            // 3. Gọi DAO để thực hiện thêm sách
            // bookDAO sẽ tìm AuthorID và CategoryID dựa trên tên, sau đó INSERT.
            bookDAO.insertBook(tenSach, tacGia, theLoai, soLuong);
            
            // 4. Làm mới form và tải lại bảng để thấy kết quả
            clearForm(); 
        }
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
       clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
   String keyword = txtTimKiem.getText().trim(); // Dùng trim() để loại bỏ khoảng trắng thừa
    
    // 2. Gọi hàm tìm kiếm trong BookDAO và truyền JTable cùng keyword
    bookDAO.searchBooks(tblBooks, keyword, categoryID);
    
    // Tùy chọn: Thông báo nếu không tìm thấy
    if (tblBooks.getRowCount() == 0) {
        MsgBox.alert(this, "Không tìm thấy sách nào khớp với từ khóa: " + keyword);
    }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if (txtMaSach.getText().isEmpty()) {
        MsgBox.alert(this, "Vui lòng chọn một cuốn sách để cập nhật.");
        return;
    }
    
    // 2. Lấy dữ liệu và kiểm tra validation
    String[] values = getFormValues();
    if (values != null) {
        String maSach = values[0];
        String tenSach = values[1];
        String tacGia = values[2];
        String theLoai = values[3];
        int soLuong = Integer.parseInt(values[4]);
        
        bookDAO.updateBook(maSach, tenSach, tacGia, theLoai, soLuong);
        clearForm(); // Làm mới form và tải lại bảng
    }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText().trim();
    if (maSach.isEmpty()) {
        MsgBox.alert(this, "Vui lòng chọn một cuốn sách để xóa.");
        return;
    }

    // 2. Yêu cầu xác nhận
    if (MsgBox.confirm(this, "Bạn có chắc chắn muốn xóa cuốn sách có Mã: " + maSach + "?")) {
        // 3. Thực hiện xóa
        bookDAO.deleteBook(maSach);
        clearForm(); // Làm mới form và tải lại bảng
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhoSachForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<Category> cboTheLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblClock;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

// ========================== XỬ LÝ SỰ KIỆN CLICK BẢNG ==========================//
    /**
     * Lấy thông tin từ hàng được chọn trong bảng tblBooks và điền vào form bên phải
     * @param evt 
     */
    private void tblBooksMouseClicked(java.awt.event.MouseEvent evt) {
    if (evt.getClickCount() == 1) {
        int selectedRow = tblBooks.getSelectedRow();
        if (selectedRow >= 0) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBooks.getModel();
            
            String maSach = model.getValueAt(selectedRow, 0).toString();
            String tenSach = model.getValueAt(selectedRow, 1).toString();
            String tenTacGia = model.getValueAt(selectedRow, 2).toString();
            String theLoaiName = model.getValueAt(selectedRow, 3).toString(); // Tên thể loại
            String soLuong = model.getValueAt(selectedRow, 4).toString();
            
            txtMaSach.setText(maSach);
            txtTenSach.setText(tenSach);
            txtTacGia.setText(tenTacGia);
            
            // --- LOGIC CHỌN ĐỐI TƯỢNG TRONG COMBOBOX ---
            selectCategoryByName(theLoaiName); 
            // ------------------------------------------
            
            txtSoLuong.setText(soLuong);
        }
    }    
}
    private void loadDataToCboTheLoai() {
    DefaultComboBoxModel<Category> model = new DefaultComboBoxModel<>();
    
    try {
        // 1. Thêm mục mặc định (CategoryID = 0)
        model.addElement(new Category(0, "--- Tất Cả Thể Loại ---")); 

        // 2. Lấy danh sách thể loại từ DB (ĐÃ SỬA LỖI GỌI DAO)
        List<Category> categories = CategoryDAO.selectAll();
        
        // 3. Thêm các Category vào Model
        for (Category cat : categories) {
            model.addElement(cat); 
        }

        // 4. Đặt Model vào JComboBox
        cboTheLoai.setModel(model);
        
        // 5. Đặt mục chọn mặc định là mục đầu tiên
        cboTheLoai.setSelectedIndex(0); 

    } catch (Exception e) {
        e.printStackTrace();
        MsgBox.alert(this, "Lỗi khi tải dữ liệu Thể loại: " + e.getMessage()); 
    }
}

private void selectCategoryByName(String categoryName) {
    // Ép kiểu model của ComboBox về DefaultComboBoxModel<Category>
    javax.swing.DefaultComboBoxModel<Category> model = (javax.swing.DefaultComboBoxModel<Category>) cboTheLoai.getModel();
    
    // Duyệt qua tất cả các phần tử trong ComboBox
    for (int i = 0; i < model.getSize(); i++) {
        Category cat = model.getElementAt(i);
        
        // So sánh Tên thể loại (Sử dụng equalsIgnoreCase để đảm bảo độ chính xác)
        if (cat.getCategoryName().equalsIgnoreCase(categoryName)) {
            cboTheLoai.setSelectedIndex(i);
            return; // Thoát ngay sau khi tìm thấy và chọn
        }
    }
    
    // Tùy chọn: Nếu không tìm thấy tên thể loại khớp, chọn mục mặc định (index 0)
    // cboTheLoai.setSelectedIndex(0); 
}

private void applyHoverEffect(JButton button, Color defaultColor, Color hoverColor) {

    button.setForeground(Color.BLACK);
    // THÊM DÒNG NÀY: Đặt màu nền ban đầu
    button.setBackground(defaultColor); 

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hoverColor);
            button.setForeground(Color.BLACK);
            setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(defaultColor);
            button.setForeground(Color.BLACK);
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    });
}

}
