/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fpoly.ui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author X1 Carbon
 */
public class WelcomeForm_1 extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeForm
     */
    private JProgressBar progress;
    private JLabel title, subtitle, loadingText;

    public WelcomeForm_1() {
        setUndecorated(true);
        setSize(750, 480);
        setLocationRelativeTo(null);
        setLayout(null);
        setBackground(new Color(0, 0, 0, 0)); // nền trong suốt

        initUI();
        fadeIn();
        runProgress();

    }

    private void initUI() {

        // nền bo góc
        JPanel panel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // nền blur giả
                g2.setColor(new Color(20, 20, 20, 210));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 40, 40);
            }
        };
        panel.setBounds(0, 0, 750, 480);
        panel.setLayout(null);

        // tiêu đề
        title = new JLabel("PHẦN MỀM");
        title.setForeground(Color.WHITE);
        title.setFont(new Font("Segoe UI", Font.BOLD, 40));
        title.setBounds(260, 60, 400, 50);

        subtitle = new JLabel("QUẢN LÝ THƯ VIỆN");
        subtitle.setForeground(Color.WHITE);
        subtitle.setFont(new Font("Segoe UI", Font.BOLD, 42));
        subtitle.setBounds(180, 120, 500, 50);

        // dòng chữ loading
        loadingText = new JLabel("Đang tải...", SwingConstants.CENTER);
        loadingText.setForeground(Color.WHITE);
        loadingText.setFont(new Font("Segoe UI", Font.BOLD, 20));
        loadingText.setBounds(0, 350, 750, 30);

        // progress bar hiện đại
        progress = new JProgressBar();
        progress.setBounds(50, 390, 650, 25);
        progress.setBorder(null);
        progress.setStringPainted(false);
        progress.setBackground(new Color(70, 70, 70));
        progress.setForeground(Color.CYAN);

        progress.setUI(new BasicProgressBarUI() {
            @Override
            protected void paintDeterminate(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                int width = progress.getWidth();
                int height = progress.getHeight();
                int value = (int) (progress.getPercentComplete() * width);
                // nền progress
                g2.setColor(new Color(60, 60, 60));
                g2.fillRoundRect(0, 0, width, height, 20, 20);
                // gradient neon
                GradientPaint gp = new GradientPaint(
                        0, 0, new Color(0, 180, 255),
                        width, height, new Color(255, 80, 80)
                );
                g2.setPaint(gp);
                g2.fillRoundRect(0, 0, value, height, 20, 20);
            }
        });
        panel.add(title);
        panel.add(subtitle);
        panel.add(loadingText);
        panel.add(progress);
        add(panel);
    }

    // Hiệu ứng fade-in
    private void fadeIn() {
        new Thread(() -> {
            try {
                for (float i = 0; i <= 1; i += 0.05) {
                    setOpacity(i);
                    Thread.sleep(30);
                }
            } catch (Exception e) {
            }
        }).start();
    }

    // Animation progress
    public void runProgress() {
        new Thread(() -> {

            String[] txt = {"Đang tải.", "Đang tải..", "Đang tải..."};
            int t = 0;

            try {
                for (int i = 0; i <= 100; i++) {

                    progress.setValue(i);
                    if (i % 10 == 0) {
                        loadingText.setText(txt[t]);
                        t = (t + 1) % txt.length;
                    }
                    Thread.sleep(30);
                }
                loadingText.setText("Hoàn thành!");
                Thread.sleep(500);
                new LoginForm().setVisible(true);
                dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 660, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quản Lí Thư Viện");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phần Mềm");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
